### PR TITLE
for proper view of saved utf-8 text

### PR DESCRIPTION
**Pull request by Slasy**

### CODE REVIEW

**Comment by p-e-w** [comment]
Since https://github.com/p-e-w/quicksafe/commit/96c7ca0f503a6ece81986b414960b5d272cdcab6, Unicode text works for me already. Can you provide instructions for producing a problem that your PR fixes?

**Comment by Slasy** [comment]
In Linux Mint (Python 2) Unicode works great. Windows 8 and Python 2.7 works too, but Windows 8 and Python 3.4 don't. So to produce problem: store some multibyte Unicode characters (for example some Czech and Japanese characters: 'čeština 日本語') using Python 3.4.

**Comment by p-e-w** [comment]
Interesting. On my Fedora 21 box with Python 3.4.1, Unicode works without problems, so it must be a Windows issue. Regrettably, I don't have access to a Windows box.

Is there also anything that needs to be done to support Unicode *passwords* in your configuration? Could you test whether you can open a file protected using a Unicode password in Python 2.7 with Python 3.4 and vice versa? I know it works on Linux, but everything seems different in the Windows world.

**Comment by Slasy** [comment]
To get support of Unicode passwords on both 2.7 and 3.4 on Windows I had to add _.encode('utf-8')_ to function _ask_password()_.
~~~
def ask_password(caption):
    return askstring(caption, '', show='*').encode('utf-8')
~~~
Now it seems it's working everywhere.

**Comment by p-e-w** [comment]
Merged. Thank you for your contribution! I have also added your second fix in https://github.com/p-e-w/quicksafe/commit/8ebecd84dd605edd16f0bcd5474746303771a45d.

Looking at the code, it now feels Unicode handling is wrong somehow. There are too many `encode`s and `decode`s for such a simple task. This should be revisited in the future, but for now, what matters is that the program works on all platforms.

**Pull request merged**
